version: '3'
services:
  server:
    container_name: demo_dev_server
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=roo
      - PGHOST=db
      - PGPASSWORD=rootinepass
      - PGDATABASE=rootine
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: demo_dev_db
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=rootine
      - POSTGRES_USER=roo
      - POSTGRES_PASSWORD=rootinepass
volumes:
  dbdata:
networks: 
  default:
    name: demo_dev_app
